enum MenuType {
  MENU_TOP,
  MENU_BOTTOM,
  MENU_LEFT,
  MENU_RIGHT,
  MENU_MIX,
  MENU_CLOSE
}

enum MenuItemType {
  MENU_SETTING,
  MENU_BACK,
  MENU_DOWNLOAD,
  MENU_MORE,
  MENU_PRE_CHAPTER,
  MENU_NEXT_CHAPTER,
  MENU_CATALOG,
  MENU_LIGHT_MODE,
  MENU_NIGHT_MODE,
  MENU_QQ,
  MENU_QZONE,
  MENU_WECHAT,
  MENU_WECHAT_MOMENT,
  MENU_CLOSE,
  MENU_LEFT_CATALOG,
  MENU_LEFT_TAG,
  MENU_LEFT_CATALOG_ITEM,
  MENU_LEFT_TAG_ITEM
}

enum MenuBottomType {
  MENU_BOTTOM_COMMON,
  MENU_BOTTOM_SETTING,
  MENU_BOTTOM_SHARE
}
